server:
  port: 8080


#  jdbc.driverClassName=org.h2.Driver
#  jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
#  jdbc.username=sa
#  jdbc.password=1234

spring:
  datasource:
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;

  h2:
    console:
      enable: true
      path: /console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
  file:
    name: logs/application.log
